DROP DATABASE IF EXISTS Escuela;
CREATE DATABASE Escuela DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
GRANT ALL PRIVILEGES ON Escuela.* TO 'escuela'@'localhost' IDENTIFIED BY 'escuela';
USE Escuela;

CREATE TABLE Maestro
(
	id		 		INT 			NOT NULL AUTO_INCREMENT,
	nombreMaestro	VARCHAR(50)		NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE Alumno
(	
	id 				INT 		NOT NULL AUTO_INCREMENT,
	matricula		CHAR(8)		NOT NULL,
	nombreAlumno	CHAR(45)	NOT NULL,
	semestre		INT		 	NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE Materia
(
	id				INT			NOT NULL AUTO_INCREMENT,
	nombreMateria	VARCHAR(45)	NOT NULL,	
	idMaestro		INT			NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
ALTER TABLE Materia ADD FOREIGN KEY (idMaestro) REFERENCES Maestro (id) ON DELETE CASCADE;

CREATE TABLE Grupo
(
	id 			INT 	NOT NULL AUTO_INCREMENT,
	nombreGrupo	CHAR(2) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE Horario
(
	id  		INT 		NOT NULL AUTO_INCREMENT,
	idAlumno	INT 		NOT NULL,
	idGrupo		INT 		NOT NULL,
	idMateria	INT 		NOT NULL,
	hora		VARCHAR(5)	NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
ALTER TABLE Horario ADD FOREIGN KEY (idAlumno) REFERENCES Alumno (id) ON DELETE CASCADE;
ALTER TABLE Horario ADD FOREIGN KEY (idGrupo) REFERENCES Grupo (id) ON DELETE CASCADE;
ALTER TABLE Horario ADD FOREIGN KEY (idMateria) REFERENCES Materia (id) ON DELETE CASCADE;
